name: Check for updates

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if image needs updating
        id: image-update
        run: |
          docker pull alpine:3.18
          docker images --format '{{.ID}}' alpine:3.18 > .github/docker-image-built-against
          git ls-remote https://github.com/samhocevar/rinetd.git main > .github/docker-rinetd-built-against
          img_needs_updating=`git status --porcelain`
          set -x
          echo "needs-updating=`[[ $img_needs_updating ]] && echo true || echo false`" >>$GITHUB_OUTPUT

      - name: Check if there are any package updates
        id: pkg-update
        run: |
          docker pull ghcr.io/digitallyrefined/tmp
          pkgs_to_update=`docker run --rm ghcr.io/digitallyrefined/tmp sh -c ' \
          apk upgrade --simulate --no-cache | { grep Upgrading || true; }'`
          set -x
          echo "needs-updating=`[[ $pkgs_to_update ]] && echo true || echo false`" >>$GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98
        with:
          driver-opts: 'image=moby/buildkit:v0.10.5'
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/digitallyrefined/tmp:latest
            ghcr.io/digitallyrefined/tmp:v3
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

