name: Check for updates

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if base image update available
        id: image-update
        run: |
          docker pull ubuntu:jammy
          docker images --format '{{.ID}}' ubuntu:jammy > .github/docker-image-built-against
          img_needs_updating=`git status --porcelain`
          set -x
          echo "needs-updating=`[[ $img_needs_updating ]] && echo true || echo false`" >>$GITHUB_OUTPUT

      - name: Check if there are any package updates
        id: pkg-update
        run: |
          docker pull ghcr.io/digitallyrefined/docker-wireguard-tunnel
          pkgs_to_update=`docker run --rm ghcr.io/digitallyrefined/docker-wireguard-tunnel bash -c ' \
          apt update > /dev/null && \
          apt -s -o Debug::NoLocking=true upgrade | { grep ^Inst || true; }'`
          set -x
          echo "needs-updating=`[[ $pkgs_to_update ]] && echo true || echo false`" >>$GITHUB_OUTPUT

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: docker-wireguard-tunnel
          tags: v2, latest
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
        if: steps.image-update.outputs.needs-updating == 'true' || steps.pkg-update.outputs.needs-updating == 'true'

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
